site_name: ieiao's Wiki

theme:
  name: material
  features:
    - content.code.copy
  logo: assets/logo.jpeg
  favicon: assets/favicon.jpeg
  language: zh

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

nav:
  - '关于': 'index.md'
  - '笔记':
    - '工具':
      - 'Linux Tips': 'tools/linux_tips.md'
      - 'PulseView': 'tools/pulseview.md'
      - 'hexdump': 'tools/hexdump.md'
      - 'gcc': 'tools/gcc.md'
      - 'make': 'tools/make.md'
    - '嵌入式开发':
      - 'Linux内核':
        - 'SOC移植实践': 'embedded-dev/linux/porting-to-new-soc/index.md'
      - '墨水屏': 'embedded-dev/epaper/index.md'
      - '旋转编码器': 'embedded-dev/rotary-encoder.md'
      - 'S905X': 'embedded-dev/amlogic/s905x/index.md'
      - 'RK3128': 'embedded-dev/rockchip/rk3128/index.md'
      - '单片机':
        - '调试工具': 'embedded-dev/MCU/dbg-tools.md'
        - 'AT Tiny85': 'embedded-dev/MCU/at-tiny85.md'
        - 'MSP430': 'embedded-dev/MCU/msp430.md'
      - 'RT-Thread': 'embedded-dev/MCU/rt-thread.md'
    - '硬件':
      - '场效应管': 'embedded-dev/fet/index.md'
  - '项目':
    - 'serprog': 'projects/serprog/index.md'
    - 'Epd-Clock': 'projects/epd-clock/index.md'
  - '博客/项目存档': 'blog-archive/index.md'
